import ImageUploadField from '../../components/admin/ImageUploadField'
import { useEffect,useState } from 'react'
import toast from 'react-hot-toast'
import { supabase } from '../../lib/supabaseClient'
import ProductImage from '../../components/products/ProductImage'
const empty={name:'',description:'',image_url:'',sort_order:0}
export default function AdminCategoriesPage(){
 const [uploading,setUploading]=useState(false)
 const [categories,setCategories]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function load(){setLoading(true);const {data,error}=await supabase.from('categories').select('*, products(count)').order('sort_order').order('name');setCategories(data||[]);setError(error?.message||'');setLoading(false)}
 useEffect(()=>{load()},[])
 async function save(e){e.preventDefault();if(saving || uploading)return;setSaving(true);const payload={...form,name:form.name.trim(),sort_order:Number(form.sort_order),image_url:form.image_url.trim()||null};const {error}=editing?await supabase.from('categories').update(payload).eq('id',editing):await supabase.from('categories').insert(payload);setSaving(false);if(error)return toast.error(error.message);toast.success('Category saved');setForm(empty);setEditing(null);load()}
 async function remove(c){if(c.products?.[0]?.count)return toast.error("Move this category's products to another category first.");if(!confirm('Delete '+c.name+'?'))return;const {error}=await supabase.from('categories').delete().eq('id',c.id);if(error)return toast.error(error.message);if(editing===c.id){setEditing(null);setForm(empty)}load()}
 return <div><h1 className="font-display text-2xl">Categories</h1><p className="mt-2 text-sm text-plum-400">Organize your gifts. Every product belongs to a category.</p><form onSubmit={save} className="mt-6 grid gap-3 rounded-2xl border border-plum-100 bg-white p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 text-lg">{editing?'Edit category':'Add category'}</h2><label className="text-sm">Name<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-lg border border-plum-100 p-2"/></label><label className="text-sm">Display order<input type="number" step="1" required value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})} className="mt-1 w-full rounded-lg border border-plum-100 p-2"/></label><label className="text-sm">Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-lg border border-plum-100 p-2"/></label><div className="sm:col-span-2"><ImageUploadField key={editing || 'new'} folder="categories" value={form.image_url} disabled={saving || uploading} onBusyChange={setUploading} onChange={image_url=>setForm(current=>({...current,image_url}))}/></div><p className="text-xs text-plum-400 sm:col-span-2">Missing or unavailable images use picture.png.</p><button disabled={saving || uploading} className="rounded-lg bg-plum-800 p-3 text-white">{saving?'Saving...':'Save category'}</button>{editing&&<button disabled={saving || uploading} type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</form>{error&&<p role="alert" className="mt-4 text-coral-600">{error}</p>}<div className="mt-6 overflow-x-auto rounded-xl border border-plum-100 bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b border-plum-100"><th className="p-4">Category</th><th>Products</th><th>Order</th><th className="p-4">Actions</th></tr></thead><tbody>{categories.map(c=><tr key={c.id} className="border-b border-plum-50"><td className="flex items-center gap-3 p-4"><ProductImage src={c.image_url} alt="" className="h-12 w-12 rounded-full object-contain"/>{c.name}</td><td>{c.products?.[0]?.count||0}</td><td>{c.sort_order}</td><td className="p-4"><button disabled={saving || uploading} className="mr-4 text-plum-600" onClick={()=>{setEditing(c.id);setForm({name:c.name,description:c.description||'',image_url:c.image_url||'',sort_order:c.sort_order})}}>Edit</button><button disabled={saving || uploading} className="text-coral-600" onClick={()=>remove(c)}>Delete</button></td></tr>)}{!categories.length&&<tr><td colSpan={4} className="p-6 text-center">{loading?'Loading categories...':'No categories yet.'}</td></tr>}</tbody></table></div></div>
}